### ISSUE TITLE
Better handling of multiple issues

### ISSUE THREAD

**Issue by mike-potter** [joachim-n/dorgflow#21]
I tend to work on a lot of different issues at the same time.  So I have lots of branches.

When I type: "dorgflow 2868879" I get the message:
"The feature branch 2868879-Wrong-user-link-in-oamessages already exists. Use the update command, rebasing first if necessary. Aborting."

Yes, I know...can you please just switch me to that branch so I don't have to type a really long "git checkout" command?

I can only use "dorgflow update" when I'm within the feature branch.  If I'm within a different feature branch, or back in master then it doesn't work.  So the error message is misleading.

So, as a feature request, I'd love to see "dorgflow issue#" switch me to the feature branch if it already exists.  Would save a lot of typing for me.

**Comment by joachim-n** [comment]
Good idea. Working on this...

**Comment by joachim-n** [comment]
Committed in 69fe70d67994d9a3510009a8970d01f1301eea3e.

Not sure when there'll be a new release, as I was hoping to get https://github.com/joachim-n/dorgflow/issues/4 in this too as I feel the amount of text output to the user has hit the point where it needs to be a bit prettier...  but I've hit a few problems with that issue...

Feel free to try the master branch though, it's stable (as that's what I use for my own work on drupal issues ;)
