### ISSUE TITLE
Before "git diff-files" you should execute "git update-index --refresh"

### ISSUE THREAD

**Issue by super-romeo** [joachim-n/dorgflow#37]
Before "git diff-files" you should execute "git update-index --refresh"
See: https://stackoverflow.com/questions/36367190/git-diff-files-output-changes-after-git-status

Otherwise, git diff-files show me modifications, that I've never done. And I have "Git repository is not clean. Aborting." exception.

[03:05 PM]-[vagrant@local]-[/var/www/drupal_8/web/modules/contrib/field_display_label]-[...]
$ git diff-files
:100644 100644 d3f52e261af30ab4a4b58077e752605caba46e93 0000000000000000000000000000000000000000 M      README.txt
:100644 100644 0dd03a509fd01506e5daecf0519683217f0cd1c0 0000000000000000000000000000000000000000 M      config/schema/field_display_label.schema.yml
:100644 100644 fda071b0a3befeb8ba58bad996bae1f3641adce6 0000000000000000000000000000000000000000 M      field_display_label.info.yml
:100644 100644 5a6dddfcd91dc02e9fde92b71a75fe33be4889e2 0000000000000000000000000000000000000000 M      field_display_label.module

[03:06 PM]-[vagrant@local]-[/var/www/drupal_8/web/modules/contrib/field_display_label]-[...]
$ git update-index --refresh

[03:06 PM]-[vagrant@local]-[/var/www/drupal_8/web/modules/contrib/field_display_label]-[$]
$ git diff-files
$

**Comment by superromeo** [comment]
Sorry for wrong info. This is because I've got project via "composer require ..." instead of "git clone".

**Comment by miloskroulik** [comment]
This helped me, otherwise `dorgflow` refuses to create a branch for the issue.`

**Comment by joachim-n** [comment]
Thanks for tracking down the info for that, @superromeo! I've been wondering how to fix this for ages!
