### ISSUE TITLE
consider using Symfony Console

### ISSUE THREAD

**Issue by joachim-n** [joachim-n/dorgflow#4]
Pros:

- provides nice formatting of output
- provides autocomplete of commands
- isolates output; easier for testing (though note that PHPUnit can handle and test for print statements in tests).

Con:

- more overhead
- need to look at how it handles a set of different commands
- ...?

**Comment by geek-merlin** [comment]
I'm looking forward to this as symfony-console / drupal-console is also on my list to refactor some tools ;-)

**Comment by joachim-n** [comment]
I've had a go at this, as I think I've now reached the point where there's enough text output to the user that it could stand to be made prettier, and making it easier to implement prompting and extra options would be good too.

I've got stuck, however. Work so far is in branch sandbox-symfony-console, and this issue in symfony docs has details: https://github.com/symfony/symfony-docs/issues/7874

**Comment by geek-merlin** [comment]
Cool, i'll look into this.

**Comment by joachim-n** [comment]
Thanks! :)

**Comment by joachim-n** [comment]
I'm working on this at the moment -- got help at SO: http://stackoverflow.com/questions/44057062/how-do-i-use-symfony-console-with-dependency-injection-without-the-symfony-fram/44057714#44057714
