### ISSUE TITLE
Create patch not in project folder

### ISSUE THREAD

**Issue by super-romeo** [joachim-n/dorgflow#40]
Maybe better create patch not in project folder, but in parent folder?

**Comment by joachim-n** [comment]
What would be the point?

**Comment by super-romeo** [comment]
After patch generation, I upload it to issue on drupal.org, move it in parent folder. And I have such folder: 
![screenshot](https://user-images.githubusercontent.com/11851470/51839030-1087ca80-2319-11e9-92a3-a09ca6721ba0.jpg)
After all I delete project folder.
Is it a best approach?

**Comment by joachim-n** [comment]
I tend to keep my project git clones for a future occasion I might work on them.

If you're deleting the project's git clone, you might as well delete the patch as well -- it's uploaded to d.org now.

Though I would recommend you don't delete anything until a patch is committed, as it might need further work or a reroll.

**Comment by frederickjh** [comment]
Try running ` git clean -df` to clean up the patch and interdiff before you re-roll your patch.

**Comment by joachim-n** [comment]
You should add .patch and .interdiff to a global .gitignore, so they are never committed.

**Comment by super-romeo** [comment]
i see. Thank you.
