### ISSUE TITLE
Patches for Drupal 8 Core broken if using drupal-composer/drupal-project

### ISSUE THREAD

**Issue by Gogowitsch** [joachim-n/dorgflow#44]
**Motivation**  
I use [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project) as a starter for all my Drupal sites. It installs a `.git` folder for Drupal Core within the `core` directory. 

**Problem**  
When creating a Core patch with dorgflow, the patch won't apply when uploading it to the Drupal.org issue queue. This is because the `core` is not in the patch. It needs to be because `git clone --branch 8.6.x https://git.drupal.org/project/drupal.git` will place the `.git` folder outside of `core`.

**Solution**  
Fix the patch file:
- Search for `([-+]{3} [ab])/(assets|config|includes|lib|misc|modules|profiles|scripts|tests|themes)/`
- Replace by `$1/core/$2/`

**Comment by joachim-n** [comment]
I don't use drupal-project when I'm working on core issues, so this isn't something I'm going to have time to work on.

I'll consider a PR that adds some special casing to the code that figures out the current project & writing patches.

You should be able to get the core/ added into the diff with the --src-prefix and --dst-prefix options to git diff.

**Comment by joachim-n** [comment]
Thanks for reporting this & for the PR. I've made a few changes to your approach, but having your code helped a lot!
