### ISSUE TITLE
Add command line help

### ISSUE THREAD

**Issue by frederickjh** [joachim-n/dorgflow#49]
Currently running `dorgflow help` returns:

![image](https://user-images.githubusercontent.com/864159/54560225-23865500-49c2-11e9-8f00-d7dfbea49940.png)

I would expect that this would list the commands that can be run (diff, status, update, apply, cleanup, purge) with **dorgflow** with a help text.

**Comment by joachim-n** [comment]
That's just standard output from Symfony Console.  To get a list of commands, use the list command (which is also standard Symfony Console).

**Comment by frederickjh** [comment]
Ah, Ok. I didn't realize that. I use several other projects that use the Symfony Console and I thought that they all list the commands when I run the command name followed by help, but it looks like I was mistaken as they just run the `list` command when the command is run without any options and the command with help returns something similar to what is seen above.

**Comment by joachim-n** [comment]
Ah yes, the difference here is that I've overridden the behaviour with no options to be the 'patch' command.
